# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
 paths:
   include:
     - src/emailservice/*

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '7ccd512e-ef0c-478c-886c-83a8c48a4414'
  imageRepository: 'emailservice'
  containerRegistry: 'prokoptocontainerr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/src/emailservice/Dockerfile'
  tag: '$(Build.BuildId)'

pool:
 name: azureagent

stages:
- stage: Build
  displayName: Build the image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build the image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: 'src/emailservice/Dockerfile'
        tags: '$(tag)'
- stage: Push
  displayName: Push the image
  jobs:
  - job: Push
    displayName: Push
    steps:
    - task: Docker@2
      displayName: Push the image to container
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'push'
        tags: '$(tag)'
