# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
 paths:
   include:
     - src/checkoutservice/*

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '62965158-9a8a-447e-a7bc-097a81fd6597'
  imageRepository: 'jerinvarghesemicroserviceappliction'
  containerRegistry: 'prokoptocontainerr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/src/checkoutservice/Dockerfile'
  tag: '$(Build.BuildId)'

pool:
 name: azureagent

stages:
- stage: Build
  displayName: Build the image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build the image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: 'checkoutserviceapp'
        command: 'build'
        Dockerfile: 'src/checkoutservice/Dockerfile'
        tags: '$(tag)'
- stage: Push
  displayName: Push the image
  jobs:
  - job: Push
    displayName: Push
    steps:
    - task: Docker@2
      displayName: Push the image to container
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'push'
        tags: '$(tag)'